image: Visual Studio 2017

init:
  - ps: Write-Host "Installing Service Fabric SDK"
  - ps: choco install MicrosoftAzure-ServiceFabric-CoreSDK --source webpi --confirm
  - ps: Write-Host "Setting up local cluster"
#  - ps: "$ENV:ProgramFiles\Microsoft SDKs\Service Fabric\ClusterSetup\DevClusterSetup.ps1"